load("//Config:buck_rule_macros.bzl", "first_party_library")

first_party_library(
    name = "WeatherForecastNetworking",
    deps = [
        "//Vendor/Alamofire:Alamofire",
    ],
    test_deps = [
        "//Vendor/Swinject:Swinject",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
)
